name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          fetch-tags: true
      - name: Debug initial state
        run: |
          echo "Initial git status:"
          git status
          echo "File in workspace:"
          ls -la

      - name: Clean any potential mess
        run: |
          git reset --hard HEAD
          git clean -fdx
          echo "Status after cleaning:"
          git status

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          
      - name: Debug project structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          echo "Go files:"
          find . -name "*.go" -type f

      - name: Initialize module
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/${{ github.repository }}
          fi
          go mod tidy

      - name: Verify build
        run: |
          go build -o tz . || \
          echo "Build failed - check your main.go location"
          [ -f "./tz" ] && ./tz --version || echo "Binary not found"

      - name: Final git check
        run: |
          echo "Final git status before GoReleaser:"
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            echo "ERROR: Still dirty! Files:"
            git status --porcelain
            exit 1
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
