name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Debug project structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          echo "Go files:"
          find . -name "*.go" -type f

      - name: Verify build
        run: |
          go mod tidy
          # Try different build paths until one works:
          go build -o tz ./cmd/tz || \
          echo "Build failed - check your main.go location"
          [ -f "./tz" ] && ./tz --version || echo "Binary not found"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
